server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://localhost:3307/metro_user_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKeymySecretKeymySecretKey123456}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
